# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "ubuntu-vm" do |vm1|
        vm1.vm.hostname = "ubuntu-vm"
        vm1.vm.box = "bento/ubuntu-20.04"
        vm1.vm.network "private_network" , ip: "192.168.33.10"
    
        # config.vm.synced_folder ".", "/vagrant", disabled: true
    
        vm1.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu-vm"
        # Display the VirtualBox GUI when booting the machine
        vb.gui = false
        
        # Customize the amount of memory on the VM:
        vb.memory = "1024"
        end
        config.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "Hello Abhishek , This is your Vagrantfile for ubuntu machine"
        SHELL
    end

    config.vm.define "centos-vm" do |vm2|
        vm2.vm.hostname = "centos-vm"
        vm2.vm.box = "bento/centos-7.2"
        vm2.vm.network "private_network" , ip: "192.168.33.20"
    
        # config.vm.synced_folder ".", "/vagrant", disabled: true
    
        vm2.vm.provider "virtualbox" do |vb|
        vb.name = "centos-vm"
        # Display the VirtualBox GUI when booting the machine
        vb.gui = false
        
        # Customize the amount of memory on the VM:
        vb.memory = "1024"
        end
        config.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "Hello Abhishek , This is your Vagrantfile for centos machine"
        SHELL
    end
end